# Generated by Django 3.1.6 on 2021-02-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(default=None)),
                ('registered_country_geoname_id', models.IntegerField(default=None)),
                ('latitude', models.FloatField(default=None)),
                ('longitude', models.FloatField(default=None)),
            ],
        ),
    ]
